apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: y27wzhz2o-go
  janus-idp.io/tekton: y27wzhz2o-go
  backstage.io/kubernetes-id: y27wzhz2o-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: y27wzhz2o-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
